### ISSUE TITLE
Get the value of a query param

### ISSUE THREAD

**Issue by balazsbotond** [balazsbotond/FluentUriBuilder#2]
Feature request from Reddit:

> Can you pull out a query string key? So if you have
> do a FluentUri.From("http://example.com/somepath?foo=bar#baz").GetParam("foo") so you can get the value of it?

Source: https://www.reddit.com/message/unread/

**Comment by Ibrahim-Islam** [comment]
@balazsbotond For this to work, using `FluentUriBuilder.From('')` should populate the private properties. At least [`queryParams`] (https://github.com/balazsbotond/FluentUriBuilder/blob/master/FluentUriBuilder/FluentUriBuilder.cs#L25). Then just the following can be done:

```
public string GetParam(string key)
{
    key.ThrowIfNullOrWhiteSpace(nameof(key));

    return this.queryParams.Find(p => p.Key == key).Value;
}
```
I can work on this if its ok. Let me know your thoughts.

**Comment by balazsbotond** [comment]
Thank you again Ibrahim, and sorry for the late reply.

Your implementation seems correct but I'm afraid the original feature request was not very well thought out. URI's can contain multiple query parameters with the same name so the key parameter of your method does not uniquely identify a parameter.

Parsing URI's is at least as inconvenient in .NET as building them. I think this functionality deserves its own, separate, complete library - maybe you could write it :)
